import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from 'next/link';
import 'bootstrap/dist/css/bootstrap.min.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
            <div className="container mt-5">
              <h1>Welcome to the Property Management System</h1>
              <p>Select an action to begin:</p>
              <div className="d-flex gap-3">
                <Link href="/login" className="btn btn-primary">
                  Login
                </Link>
                <Link href="/dashboard" className="btn btn-secondary">
                  Go to Dashboard
                </Link>
              </div>
            </div>       
        </main>
        <footer className={styles.footer}>
        <a 
            href="https://www.humanitarianoperations.org/" 
            target="_blank" 
            rel="noopener noreferrer"          
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Humanitarian Operations
          </a>  
        </footer>
      </div>
    </>
  );
}
